import { Router } from 'express';
import { z } from 'zod';
import { getDb, testConnection } from '../db.js';
import { adminUsers, siteSettings } from '../../shared/schema.js';
import { generateSecrets } from '../utils/token.js';
import bcrypt from 'bcryptjs';
import fs from 'fs';
import path from 'path';
import { config, refreshSecretsFromEnv } from '../config.js';

const router = Router();

const SAFE_TEXT = /^[^\r\n]+$/;
const safeLine = z.string().regex(SAFE_TEXT, 'Line breaks are not allowed');

const setupSchema = z.object({
  appName: safeLine.min(1).max(100),
  appUrl: z.string().url().max(500),
  appPort: z.coerce.number().int().min(1).max(65535),
  dbHost: safeLine.min(1).max(255),
  dbPort: z.coerce.number().int().min(1).max(65535),
  dbName: z.string().regex(/^[a-zA-Z0-9_\-]+$/).min(1).max(63),
  dbUser: z.string().regex(/^[a-zA-Z0-9_\-]+$/).min(1).max(63),
  dbPassword: z.string().min(1).max(255),
  adminEmail: z.string().email().max(255),
  adminPassword: z.string().min(8).max(255),
  adminName: safeLine.min(1).max(255),
});

function assertNotCompleted(): { done: boolean; body?: { success: false; error: string } } {
  if (config.setupDone) {
    return {
      done: true,
      body: { success: false, error: 'Setup already completed' },
    };
  }
  return { done: false };
}

function buildDbUrl(c: { dbUser: string; dbPassword: string; dbHost: string; dbPort: number; dbName: string }): string {
  const user = encodeURIComponent(c.dbUser);
  const pass = encodeURIComponent(c.dbPassword);
  const host = encodeURIComponent(c.dbHost);
  return `postgresql://${user}:${pass}@${host}:${c.dbPort}/${encodeURIComponent(c.dbName)}`;
}

function escapeEnv(v: string): string {
  return v.replace(/\r?\n/g, ' ');
}

router.get('/status', (_req, res) => {
  res.json({ success: true, data: { completed: config.setupDone } });
});

router.post('/test-db', async (req, res) => {
  const gate = assertNotCompleted();
  if (gate.done) {
    res.status(403).json(gate.body);
    return;
  }
  try {
    const body = setupSchema.pick({ dbHost: true, dbPort: true, dbName: true, dbUser: true, dbPassword: true }).parse(req.body);
    const url = buildDbUrl(body);
    const ok = await testConnection(url);
    res.json({ success: true, data: { connected: ok } });
  } catch (error) {
    if (error instanceof z.ZodError) {
      res.status(400).json({ success: false, error: error.errors[0].message });
      return;
    }
    res.json({ success: true, data: { connected: false } });
  }
});

router.post('/complete', async (req, res) => {
  const gate = assertNotCompleted();
  if (gate.done) {
    res.status(403).json(gate.body);
    return;
  }
  try {
    const cfg = setupSchema.parse(req.body);
    const dbUrl = buildDbUrl(cfg);

    const connected = await testConnection(dbUrl);
    if (!connected) {
      res.status(400).json({ success: false, error: 'Database connection failed' });
      return;
    }

    const secrets = generateSecrets();

    const envContent =
      `# DownAir Configuration - Generated by Setup Wizard\n` +
      `APP_NAME=${escapeEnv(cfg.appName)}\n` +
      `APP_URL=${escapeEnv(cfg.appUrl)}\n` +
      `APP_PORT=${cfg.appPort}\n` +
      `NODE_ENV=production\n` +
      `\n` +
      `DATABASE_URL=${dbUrl}\n` +
      `DB_SSL=false\n` +
      `\n` +
      `JWT_SECRET=${secrets.jwtSecret}\n` +
      `ENCRYPTION_KEY=${secrets.encryptionKey}\n` +
      `HMAC_SECRET=${secrets.hmacSecret}\n` +
      `\n` +
      `ADMIN_EMAIL=${escapeEnv(cfg.adminEmail)}\n` +
      `\n` +
      `SETUP_COMPLETED=true\n`;

    const envPath = path.resolve(process.cwd(), '.env');
    fs.writeFileSync(envPath, envContent, { encoding: 'utf8', mode: 0o600 });

    process.env.DATABASE_URL = dbUrl;
    process.env.JWT_SECRET = secrets.jwtSecret;
    process.env.ENCRYPTION_KEY = secrets.encryptionKey;
    process.env.HMAC_SECRET = secrets.hmacSecret;
    process.env.SETUP_COMPLETED = 'true';
    refreshSecretsFromEnv();

    try {
      const db = getDb(dbUrl);
      const passwordHash = await bcrypt.hash(cfg.adminPassword, 12);
      await db.insert(adminUsers).values({
        email: cfg.adminEmail,
        passwordHash,
        name: cfg.adminName,
      }).onConflictDoNothing();

      await db.insert(siteSettings).values([
        { key: 'app_name', value: cfg.appName },
        { key: 'app_url', value: cfg.appUrl },
        { key: 'app_port', value: String(cfg.appPort) },
      ]).onConflictDoNothing();
    } catch (dbError) {
      // eslint-disable-next-line no-console
      console.error('DB seed error:', dbError);
    }

    res.json({ success: true, message: 'Setup completed successfully' });
  } catch (error) {
    if (error instanceof z.ZodError) {
      res.status(400).json({ success: false, error: error.errors[0].message });
      return;
    }
    res.status(500).json({ success: false, error: 'Setup failed' });
  }
});

export default router;
