import { Router } from 'express';
import { z } from 'zod';
import { getDb, testConnection } from '../db.js';
import { adminUsers, siteSettings } from '../../shared/schema.js';
import { generateSecrets } from '../utils/token.js';
import { eq } from 'drizzle-orm';
import bcrypt from 'bcryptjs';
import fs from 'fs';
import path from 'path';

const router = Router();

const setupSchema = z.object({
  appName: z.string().min(1),
  appUrl: z.string().url(),
  appPort: z.number().min(1).max(65535),
  dbHost: z.string().min(1),
  dbPort: z.number().min(1).max(65535),
  dbName: z.string().min(1),
  dbUser: z.string().min(1),
  dbPassword: z.string().min(1),
  adminEmail: z.string().email(),
  adminPassword: z.string().min(8),
  adminName: z.string().min(1),
});

router.get('/status', (_req, res) => {
  const completed = process.env.SETUP_COMPLETED === 'true';
  res.json({ success: true, data: { completed } });
});

router.post('/test-db', async (req, res) => {
  try {
    const { dbHost, dbPort, dbName, dbUser, dbPassword } = req.body as {
      dbHost: string;
      dbPort: number;
      dbName: string;
      dbUser: string;
      dbPassword: string;
    };
    const url = `postgresql://${dbUser}:${dbPassword}@${dbHost}:${dbPort}/${dbName}`;
    const ok = await testConnection(url);
    res.json({ success: true, data: { connected: ok } });
  } catch {
    res.json({ success: true, data: { connected: false } });
  }
});

router.post('/complete', async (req, res) => {
  try {
    const config = setupSchema.parse(req.body);
    const dbUrl = `postgresql://${config.dbUser}:${config.dbPassword}@${config.dbHost}:${config.dbPort}/${config.dbName}`;

    const connected = await testConnection(dbUrl);
    if (!connected) {
      res.status(400).json({ success: false, error: 'Database connection failed' });
      return;
    }

    const secrets = generateSecrets();

    const envContent = `# DownAir Configuration - Generated by Setup Wizard
APP_NAME=${config.appName}
APP_URL=${config.appUrl}
APP_PORT=${config.appPort}
NODE_ENV=production

DATABASE_URL=${dbUrl}

JWT_SECRET=${secrets.jwtSecret}
ENCRYPTION_KEY=${secrets.encryptionKey}
HMAC_SECRET=${secrets.hmacSecret}

ADMIN_EMAIL=${config.adminEmail}
ADMIN_PASSWORD=${config.adminPassword}

SETUP_COMPLETED=true
`;

    const envPath = path.resolve(process.cwd(), '.env');
    fs.writeFileSync(envPath, envContent, 'utf8');

    process.env.DATABASE_URL = dbUrl;
    process.env.JWT_SECRET = secrets.jwtSecret;
    process.env.ENCRYPTION_KEY = secrets.encryptionKey;
    process.env.HMAC_SECRET = secrets.hmacSecret;
    process.env.SETUP_COMPLETED = 'true';

    try {
      const { drizzle } = await import('drizzle-orm/node-postgres');
      const pg = await import('pg');
      const schema = await import('../../shared/schema.js');

      const pool = new pg.Pool({ connectionString: dbUrl, ssl: false });
      const db = drizzle(pool, { schema });

      const passwordHash = await bcrypt.hash(config.adminPassword, 12);

      await db.insert(adminUsers).values({
        email: config.adminEmail,
        passwordHash,
        name: config.adminName,
      }).onConflictDoNothing();

      await db.insert(siteSettings).values([
        { key: 'app_name', value: config.appName },
        { key: 'app_url', value: config.appUrl },
        { key: 'app_port', value: String(config.appPort) },
      ]).onConflictDoNothing();
    } catch (dbError) {
      console.error('DB seed error:', dbError);
    }

    res.json({ success: true, message: 'Setup completed successfully' });
  } catch (error) {
    if (error instanceof z.ZodError) {
      res.status(400).json({ success: false, error: error.errors[0].message });
      return;
    }
    res.status(500).json({ success: false, error: 'Setup failed' });
  }
});

export default router;
