import 'dotenv/config';
import { drizzle } from 'drizzle-orm/node-postgres';
import pg from 'pg';
import * as schema from '../shared/schema.js';

const { Pool } = pg;

function h2(t: string): string { return `<h2>${t}</h2>`; }
function h3(t: string): string { return `<h3>${t}</h3>`; }
function p(t: string): string { return `<p>${t}</p>`; }
function ul(items: string[]): string { return `<ul>${items.map(i => `<li>${i}</li>`).join('')}</ul>`; }
function ol(items: string[]): string { return `<ol>${items.map(i => `<li>${i}</li>`).join('')}</ol>`; }
function tip(t: string): string { return `<blockquote><strong>Pro Tip:</strong> ${t}</blockquote>`; }
function warn(t: string): string { return `<blockquote><strong>Common Pitfall:</strong> ${t}</blockquote>`; }

interface Topic {
  title: string;
  slug: string;
  intro: string;
  sections: { heading: string; content: string }[];
  codeExample?: string;
  conclusion: string;
}

function buildPage(topic: Topic, category: string): schema.NewContentPage {
  let content = p(topic.intro);
  for (const s of topic.sections) { content += h2(s.heading) + s.content; }
  if (topic.codeExample) { content += h2('Code Example') + `<pre><code>${topic.codeExample}</code></pre>`; }
  content += h2('Pro Tips') + tip('Practice hands-on with real projects for best results') + tip('Follow official documentation alongside community resources');
  content += h2('Common Pitfalls') + warn('Avoid skipping fundamentals - they matter at every level') + warn('Never deploy to production without thorough testing');
  content += h2('Conclusion') + p(topic.conclusion);
  content += `<p><strong>Ready to download your favorite content?</strong> Try our <a href="/">free social media downloader</a> while you're here. We also have more <a href="/guides">tech guides</a> covering servers, networking, cybersecurity, cloud computing, and more.</p>`;
  return {
    slug: topic.slug,
    title: topic.title,
    category,
    metaDescription: topic.intro.slice(0, 160),
    content,
    isPublished: true,
  };
}

const TOPICS: Record<string, Topic[]> = {
  'Servers': [
    { title: 'Apache vs Nginx: Complete Performance Comparison', slug: 'apache-vs-nginx-comparison', intro: 'Choosing between Apache and Nginx is one of the most critical decisions when setting up a web server. Both have dominated the web server market for decades, but they excel in different areas. This comprehensive guide breaks down the differences to help you make an informed decision.', sections: [{ heading: 'Architecture Overview', content: p('Apache uses a process-driven approach, spawning a new process or thread for each connection. This makes it highly configurable but can consume more memory under heavy load. Nginx uses an event-driven architecture that handles thousands of connections within a single worker process, making it incredibly efficient for static content delivery.') + p('According to the latest web server surveys, Nginx powers over 34% of all websites, while Apache serves approximately 31%. Both are battle-tested and production-ready.') }, { heading: 'Performance Benchmarks', content: p('In static content serving, Nginx consistently outperforms Apache by 2-3x. For dynamic content with PHP-FPM, the difference narrows significantly. Key metrics to consider include:') + ul(['Concurrent connections handling', 'Memory usage per connection', 'Request processing latency', 'SSL/TLS termination speed', 'Static file throughput']) }, { heading: 'Configuration Comparison', content: p('Apache uses distributed configuration through .htaccess files, allowing directory-level overrides. Nginx uses a centralized configuration approach, which is more performant but less flexible for shared hosting environments.') }], codeExample: '# Nginx server block\nserver {\n    listen 80;\n    server_name example.com;\n    root /var/www/html;\n    location / { try_files $uri $uri/ =404; }\n    location ~ \\.php$ {\n        fastcgi_pass unix:/run/php/php-fpm.sock;\n        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;\n        include fastcgi_params;\n    }\n}', conclusion: 'For most modern applications, Nginx is the preferred choice due to its efficiency and event-driven architecture. However, Apache remains excellent for scenarios requiring per-directory configuration or extensive module support.' },
    { title: 'Server Hardening: Essential Security Best Practices', slug: 'server-hardening-security-guide', intro: 'Server hardening is the process of securing a server by reducing its attack surface. This involves configuring the operating system, removing unnecessary services, implementing access controls, and establishing monitoring.', sections: [{ heading: 'Initial Server Setup', content: p('Every server hardening process should start with the basics. First, update all system packages to their latest versions. Then, create a non-root user with sudo privileges and disable direct root login via SSH.') + ol(['Update all system packages', 'Create a sudo user', 'Configure SSH keys and disable password auth', 'Install and configure UFW firewall', 'Set up automatic security updates']) }, { heading: 'Firewall Configuration', content: p('A properly configured firewall is your first line of defense. UFW provides an easy-to-use interface for iptables. Only open the ports you absolutely need.') }, { heading: 'Intrusion Detection', content: p('Install fail2ban to automatically block suspicious IP addresses. Set up log monitoring with tools like Logwatch. Consider deploying OSSEC or Wazuh for host-based intrusion detection.') }], codeExample: '# /etc/sysctl.conf hardening\nnet.ipv4.conf.all.rp_filter = 1\nnet.ipv4.icmp_echo_ignore_broadcasts = 1\nnet.ipv4.conf.all.accept_redirects = 0\nnet.ipv4.tcp_syncookies = 1\nkernel.randomize_va_space = 2', conclusion: 'Server hardening is an ongoing process, not a one-time task. Regularly audit your security configuration and stay informed about new vulnerabilities.' },
    { title: 'Load Balancing: Strategies for High-Traffic Applications', slug: 'load-balancing-strategies-guide', intro: 'Load balancing distributes incoming network traffic across multiple servers to ensure no single server bears too much demand. This is critical for maintaining application availability and responsiveness during traffic spikes.', sections: [{ heading: 'Load Balancing Algorithms', content: p('Different algorithms suit different use cases. Round Robin distributes requests sequentially. Least Connections sends traffic to the server with fewest active connections. IP Hash ensures session persistence. Weighted Round Robin allocates more traffic to more powerful servers.') }, { heading: 'Layer 4 vs Layer 7', content: p('Layer 4 load balancers route traffic based on IP and port, making them fast. Layer 7 load balancers can route based on HTTP headers, cookies, and URL paths. HAProxy and Nginx support both layers.') }], codeExample: '# HAProxy configuration\nfrontend http_front\n    bind *:80\n    default_backend http_back\n\nbackend http_back\n    balance leastconn\n    option httpchk GET /health\n    server web1 10.0.0.1:8080 check\n    server web2 10.0.0.2:8080 check\n    server web3 10.0.0.3:8080 check backup', conclusion: 'Load balancing is essential for any application that needs to scale. Start with Nginx or HAProxy and evolve as your traffic grows.' },
    { title: 'Reverse Proxy Setup: Complete Configuration Guide', slug: 'reverse-proxy-setup-guide', intro: 'A reverse proxy sits between clients and backend servers, forwarding requests and providing benefits like load balancing, SSL termination, caching, and security.', sections: [{ heading: 'Benefits of Reverse Proxies', content: ul(['SSL/TLS termination and certificate management', 'Static content caching and compression', 'Rate limiting and DDoS protection', 'Load balancing across multiple backends', 'Request routing based on URL patterns']) }, { heading: 'Nginx Reverse Proxy Configuration', content: p('Nginx is the most popular choice for reverse proxy setups. Its configuration is straightforward yet powerful, supporting upstream blocks, health checks, and advanced routing.') }], codeExample: '# Nginx reverse proxy with SSL\nserver {\n    listen 443 ssl http2;\n    server_name example.com;\n    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;\n    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;\n    location /api/ {\n        proxy_pass http://backend:3000/;\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n    }\n}', conclusion: 'A reverse proxy is fundamental to modern web architecture. Whether you choose Nginx, HAProxy, or Traefik, proper configuration ensures security, performance, and reliability.' },
    { title: 'SSL/TLS Configuration: Securing Web Communications', slug: 'ssl-tls-configuration-guide', intro: 'SSL/TLS encryption is non-negotiable for modern web applications. Properly configuring your SSL/TLS setup ensures data privacy and prevents man-in-the-middle attacks.', sections: [{ heading: 'Understanding TLS 1.3', content: p('TLS 1.3 reduces the handshake from two round trips to one, improving connection speed. It removes support for outdated cryptographic algorithms and uses modern AEAD ciphers.') }, { heading: 'Certificate Management', content: p('Use Let\'s Encrypt with certbot for automated certificate provisioning. For enterprise environments, consider HashiCorp Vault or cert-manager for Kubernetes.') }], conclusion: 'Proper SSL/TLS configuration protects your users. Stay current with best practices and regularly audit your configuration using SSL Labs.' },
    { title: 'Server Monitoring: Tools and Strategies', slug: 'server-monitoring-tools-guide', intro: 'Effective server monitoring is essential for maintaining performance, detecting issues before they impact users, and planning capacity.', sections: [{ heading: 'Metrics to Monitor', content: ul(['CPU utilization (user, system, iowait, idle)', 'Memory usage (used, cached, available)', 'Disk usage and I/O operations per second', 'Network bandwidth and packet statistics', 'Application response time and error rates']) }, { heading: 'Prometheus and Grafana Stack', content: p('Prometheus collects and stores metrics as time series data. Grafana provides beautiful dashboards for visualization. Together, they form the most popular open-source monitoring stack.') }], conclusion: 'Monitoring is not optional. Invest time in setting up comprehensive monitoring and alerting from day one.' },
    { title: 'Rack Infrastructure: Data Center Best Practices', slug: 'rack-infrastructure-guide', intro: 'Proper rack infrastructure is the physical foundation of reliable IT operations. From cable management to cooling, every detail matters.', sections: [{ heading: 'Rack Organization', content: p('Follow standard practices: network equipment at the top, servers in the middle, storage at the bottom. Use cable management arms and label everything clearly.') }, { heading: 'Cooling and Environment', content: p('Hot aisle/cold aisle configuration is the standard. Monitor temperature and humidity in real-time. Target 64-80F and 40-60% relative humidity.') }], conclusion: 'Physical infrastructure is as important as software. A well-organized rack reduces downtime and extends equipment life.' },
    { title: 'Bare Metal vs VPS: Choosing the Right Hosting', slug: 'bare-metal-vs-vps-hosting', intro: 'The choice between bare metal servers and VPS impacts your performance, cost, and operational complexity. This guide helps you make the right decision for your workload.', sections: [{ heading: 'Bare Metal Servers', content: p('Bare metal provides dedicated hardware with no virtualization overhead. They offer consistent performance and predictable costs for high-compute workloads.') }, { heading: 'Virtual Private Servers', content: p('VPS instances provide flexible, scalable computing at lower cost. The trade-off is shared hardware with potential noisy neighbor effects and limited hardware customization.') }], conclusion: 'Many successful architectures combine both approaches. Use bare metal for databases and VPS for web servers.' },
    { title: 'cPanel Alternatives: Modern Server Management Panels', slug: 'cpanel-alternatives-server-panels', intro: 'With cPanel\'s significant price increases, many users are seeking alternatives. This guide reviews the best modern server management panels.', sections: [{ heading: 'Top Alternatives', content: ul(['<strong>CloudPanel:</strong> Free, focused on PHP/Node.js with Nginx integration', '<strong>CyberPanel:</strong> Open source with OpenLiteSpeed, excellent for WordPress', '<strong>aaPanel:</strong> Feature-rich free panel with modular architecture', '<strong>DirectAdmin:</strong> Affordable commercial alternative', '<strong>HestiaCP:</strong> Debian-focused, completely free', '<strong>Plesk:</strong> Premium option with excellent Docker support']) }], conclusion: 'Modern alternatives to cPanel are mature and feature-rich. The best choice depends on your specific needs and budget.' },
    { title: 'Server Migration: Zero-Downtime Strategies', slug: 'server-migration-zero-downtime', intro: 'Server migration can result in data loss and downtime if done incorrectly. This guide provides a systematic approach to achieve zero-downtime migration.', sections: [{ heading: 'Pre-Migration Planning', content: ol(['Inventory all services and dependencies', 'Set up the new server with identical software', 'Configure DNS with low TTL 48 hours before', 'Test all services on the new server', 'Plan the data sync strategy']) }, { heading: 'DNS Cutover', content: p('Reduce DNS TTL to 300 seconds at least 48 hours before migration. Keep the old server running for at least 72 hours after DNS change as a fallback.') }], conclusion: 'A successful zero-downtime migration requires meticulous planning, thorough testing, and a reliable rollback strategy.' },
    { title: 'HTTP/2 and HTTP/3: Modern Web Server Protocols', slug: 'http2-http3-protocols-guide', intro: 'HTTP/2 and HTTP/3 represent major leaps in web protocol efficiency. Understanding their features can significantly improve your website performance.', sections: [{ heading: 'HTTP/2 Features', content: p('HTTP/2 introduces multiplexing, header compression with HPACK, server push, and stream prioritization. These eliminate the head-of-line blocking of HTTP/1.1.') }, { heading: 'HTTP/3 and QUIC', content: p('HTTP/3 uses QUIC instead of TCP, eliminating transport-layer head-of-line blocking. QUIC integrates TLS 1.3 directly, reducing connection time.') }], conclusion: 'Adopting HTTP/2 is straightforward and provides immediate benefits. HTTP/3 adoption is growing rapidly.' },
    { title: 'Web Server Caching Strategies', slug: 'web-server-caching-strategies', intro: 'Effective caching is one of the most impactful optimizations. From browser caching to CDN to server-side caching, each layer provides different benefits.', sections: [{ heading: 'Cache Layers', content: p('A comprehensive strategy uses multiple layers: browser cache, CDN cache, reverse proxy cache, application cache (Redis/Memcached), and database query cache.') }, { heading: 'Cache Headers', content: p('Configure Cache-Control, ETag, Last-Modified, and Vary headers properly. Use max-age for static assets, no-cache with ETag for dynamic content.') }], conclusion: 'A well-designed caching strategy can reduce server load by 90% and dramatically improve response times.' },
    { title: 'Server Log Management and Analysis', slug: 'server-log-management-guide', intro: 'Server logs are invaluable for troubleshooting, security auditing, and performance analysis. Effective log management ensures you can find information when you need it.', sections: [{ heading: 'Log Types', content: p('Key logs include system logs, authentication logs, web server access/error logs, application logs, and database logs. Each provides different insights.') }, { heading: 'Centralized Logging', content: p('Use the ELK stack or Grafana Loki for centralized collection. Structured JSON logging makes searching and filtering much easier.') }], conclusion: 'Effective log management transforms logs from a storage burden into a powerful debugging and analysis tool.' },
    { title: 'Containerization for Servers: Docker Best Practices', slug: 'server-docker-containerization', intro: 'Docker containerization has revolutionized server deployment. Containers provide consistent environments, fast deployment, and efficient resource utilization.', sections: [{ heading: 'Multi-Stage Builds', content: p('Multi-stage builds dramatically reduce image size by separating build and runtime stages. A Node.js app can go from 1GB build to 100MB runtime image.') }], codeExample: '# Multi-stage Dockerfile\nFROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build\n\nFROM node:20-alpine\nWORKDIR /app\nCOPY --from=builder /app/dist ./dist\nCOPY --from=builder /app/node_modules ./node_modules\nEXPOSE 3000\nCMD ["node", "dist/server.js"]', conclusion: 'Docker simplifies deployment and improves consistency. Master fundamentals and adopt best practices early.' },
    { title: 'Server Performance Tuning and Optimization', slug: 'server-performance-tuning', intro: 'Server performance tuning involves optimizing hardware utilization, software configuration, and application design to maximize throughput and minimize latency.', sections: [{ heading: 'CPU Optimization', content: p('Profile your application to identify CPU bottlenecks. Use top, htop, and perf tools. Optimize database queries and implement caching.') }, { heading: 'Network Optimization', content: p('Tune TCP parameters including buffer sizes, keepalive settings, and connection queue lengths. Enable TCP Fast Open and HTTP/2.') }], conclusion: 'Performance tuning is systematic: always measure, change one thing at a time, and document results.' },
  ],
  'Networking': [
    { title: 'TCP/IP Deep Dive: Understanding Internet Protocols', slug: 'tcp-ip-deep-dive-guide', intro: 'TCP/IP is the fundamental protocol suite powering the internet. Understanding it deeply is essential for network engineers and developers building networked applications.', sections: [{ heading: 'The TCP Three-Way Handshake', content: p('Every TCP connection begins with SYN, SYN-ACK, ACK. The client sends a SYN packet, the server responds with SYN-ACK, and the client completes with ACK.') }, { heading: 'Congestion Control', content: p('Modern TCP uses CUBIC or BBR algorithms. BBR, developed by Google, can achieve significantly higher throughput on high-bandwidth networks.') }], conclusion: 'A deep understanding of TCP/IP is invaluable for troubleshooting network issues and optimizing application performance.' },
    { title: 'DNS Explained: Domain Name System Deep Dive', slug: 'dns-explained-guide', intro: 'DNS translates human-readable domain names into IP addresses. Understanding DNS is crucial for web developers, system administrators, and network engineers.', sections: [{ heading: 'How DNS Resolution Works', content: ol(['Browser checks local cache', 'OS resolver cache checked', 'Recursive resolver queried', 'Root server queried for TLD info', 'TLD server queried for authoritative server', 'Authoritative server provides the IP address']) }, { heading: 'DNS Record Types', content: p('Essential types include A (IPv4), AAAA (IPv6), CNAME (alias), MX (mail), TXT (SPF, DKIM), NS (name servers), and SOA (start of authority).') }], conclusion: 'Proper DNS configuration ensures fast resolution, reliability, and security for your web infrastructure.' },
    { title: 'VPN Protocols Compared: OpenVPN, WireGuard, IPSec', slug: 'vpn-protocols-comparison', intro: 'VPNs rely on various protocols to establish secure connections. Each offers different trade-offs between speed, security, and compatibility.', sections: [{ heading: 'WireGuard', content: p('WireGuard is the newest VPN protocol with only ~4,000 lines of code, minimal attack surface, and modern cryptographic primitives. It is built into the Linux kernel.') }, { heading: 'OpenVPN', content: p('OpenVPN is the most widely deployed open-source VPN. It supports UDP/TCP, works across NAT, and is highly configurable but has higher overhead than WireGuard.') }], conclusion: 'WireGuard is the future of VPN protocols. For maximum compatibility, OpenVPN remains the safest choice.' },
    { title: 'Firewall Configuration: iptables and nftables', slug: 'firewall-configuration-iptables-nftables', intro: 'Firewalls are the first line of defense in network security. Understanding iptables and nftables is essential for securing Linux servers.', sections: [{ heading: 'nftables: The Modern Replacement', content: p('nftables replaces iptables with a unified framework offering better performance, simpler syntax, and atomic rule updates. Most modern distributions have adopted it as default.') }], codeExample: '# nftables basic firewall\n#!/usr/sbin/nft -f\ntable inet firewall {\n    chain input {\n        type filter hook input priority 0; policy drop;\n        ct state established,related accept\n        iif lo accept\n        tcp dport { 22, 80, 443 } accept\n    }\n}', conclusion: 'Master firewall configuration to build a strong security foundation. nftables is the future.' },
    { title: 'Network Troubleshooting: Diagnostic Tools', slug: 'network-troubleshooting-guide', intro: 'Network issues can be among the most frustrating problems. This guide covers systematic troubleshooting methods and essential diagnostic tools.', sections: [{ heading: 'Essential Tools', content: ul(['<strong>ping:</strong> Test basic connectivity and latency', '<strong>traceroute/mtr:</strong> Identify routing issues', '<strong>nslookup/dig:</strong> DNS query testing', '<strong>ss:</strong> View active connections and ports', '<strong>tcpdump:</strong> Packet capture and analysis', '<strong>nmap:</strong> Port scanning and service detection', '<strong>iperf3:</strong> Network bandwidth testing']) }], conclusion: 'Systematic troubleshooting using the right tools resolves most network issues quickly.' },
    { title: 'Wi-Fi 6E and Wi-Fi 7: Next-Generation Wireless', slug: 'wifi-6e-7-next-gen-wireless', intro: 'Wi-Fi 6E and Wi-Fi 7 represent significant leaps in wireless technology with faster speeds, lower latency, and better performance in dense environments.', sections: [{ heading: 'Wi-Fi 6E: 6 GHz Expansion', content: p('Wi-Fi 6E extends into the 6 GHz band, providing up to 1,200 MHz of additional spectrum. This dramatically reduces congestion and enables gigabit speeds.') }, { heading: 'Wi-Fi 7 Features', content: p('Wi-Fi 7 introduces 320 MHz channels, 4K QAM, Multi-Link Operation, and theoretical speeds up to 46 Gbps.') }], conclusion: 'Wi-Fi 6E and 7 are transformative for wireless networking. Plan upgrades carefully and ensure your wired infrastructure can support the increased throughput.' },
    { title: 'Subnet Calculators and IP Addressing Guide', slug: 'subnet-calculator-ip-addressing', intro: 'IP subnetting is a fundamental skill for network engineers. This guide covers subnet calculation, CIDR notation, and practical addressing strategies.', sections: [{ heading: 'CIDR Notation', content: p('CIDR expresses network masks as a suffix (/24 = 255.255.255.0). A /24 has 256 addresses, a /25 has 128. Formula: 2^(32-prefix) for total addresses.') }, { heading: 'VLSM and Subnet Design', content: p('Variable Length Subnet Masking allows different subnet sizes within the same network, optimizing address utilization.') }], conclusion: 'Master IP subnetting through practice. Use tools like ipcalc for verification, but understand the math.' },
    { title: 'BGP Routing: Border Gateway Protocol Explained', slug: 'bgp-routing-explained', intro: 'BGP is the protocol that makes the internet work, routing traffic between autonomous systems to exchange reachability information.', sections: [{ heading: 'How BGP Works', content: p('BGP is a path-vector protocol that exchanges routing information between autonomous systems. It selects the best path based on attributes like AS-PATH length and LOCAL_PREF.') }, { heading: 'BGP Security', content: p('RPKI validates route announcements against cryptographic certificates. Implement RPKI to prevent route hijacking.') }], conclusion: 'BGP is the backbone of internet routing. Understanding it is essential for network engineers working at scale.' },
    { title: 'Network Security Best Practices', slug: 'network-security-best-practices', intro: 'Network security encompasses policies, practices, and tools to protect infrastructure and data from unauthorized access, attacks, and damage.', sections: [{ heading: 'Defense in Depth', content: p('Implement multiple layers: perimeter firewalls, network segmentation, intrusion detection, encrypted communications, ACLs, and endpoint protection.') }, { heading: 'Zero Trust Networking', content: p('Zero Trust assumes no implicit trust. Verify every request, enforce least privilege, and implement continuous monitoring.') }], conclusion: 'Network security is an ongoing process. Stay current with threats and implement defense in depth.' },
    { title: 'Software-Defined Networking (SDN) Guide', slug: 'software-defined-networking-guide', intro: 'SDN decouples the network control plane from the data plane, enabling programmatic control of network infrastructure for automation and centralized management.', sections: [{ heading: 'SDN Architecture', content: p('SDN separates into three layers: application, control (SDN controller), and infrastructure. The controller communicates with switches via protocols like OpenFlow.') }], conclusion: 'SDN transforms network management from manual configuration to programmatic automation.' },
    { title: 'Network Automation with Python and Ansible', slug: 'network-automation-python-ansible', intro: 'Network automation eliminates manual configuration, reduces errors, and enables rapid deployment. Python and Ansible are the leading tools.', sections: [{ heading: 'Python for Networking', content: p('Libraries like Netmiko, NAPALM, and Nornir provide powerful abstractions for device interaction, configuration backup, and bulk changes.') }], codeExample: '# Ansible network playbook\n- name: Configure interfaces\n  hosts: switches\n  tasks:\n    - name: Set interface config\n      cisco.ios.ios_config:\n        lines:\n          - description Managed by Ansible\n          - no shutdown\n        parents: interface GigabitEthernet0/1', conclusion: 'Network automation is no longer optional. Start small and gradually automate more complex tasks.' },
    { title: 'VLAN Configuration and Management', slug: 'vlan-configuration-management', intro: 'Virtual LANs segment a physical network into multiple logical networks, improving security, performance, and manageability.', sections: [{ heading: 'VLAN Fundamentals', content: p('VLANs operate at Layer 2, grouping devices by function or security requirement. IEEE 802.1Q is the standard tagging protocol.') }], conclusion: 'Proper VLAN design is foundational to a well-organized network. Plan carefully and document thoroughly.' },
    { title: 'Network Monitoring with SNMP and SNMPv3', slug: 'network-monitoring-snmp-guide', intro: 'SNMP is the standard protocol for monitoring network devices. This guide covers SNMPv3 security and monitoring best practices.', sections: [{ heading: 'SNMP Versions', content: p('SNMPv1/v2c use clear-text community strings. SNMPv3 adds authentication, encryption, and access control. Always use SNMPv3 in production.') }], conclusion: 'SNMP remains essential for network visibility. Migrate to SNMPv3 for security.' },
    { title: 'DNS Security: DNSSEC and DoH/DoT', slug: 'dns-security-dnssec-doh', intro: 'DNS security extensions protect against DNS spoofing and cache poisoning. DNS over HTTPS and DNS over TLS encrypt DNS queries for privacy.', sections: [{ heading: 'DNSSEC', content: p('DNSSEC adds cryptographic signatures to DNS records, allowing resolvers to verify authenticity. Implement DNSSEC on your authoritative zones.') }, { heading: 'Encrypted DNS', content: p('DoH (DNS over HTTPS) and DoT (DNS over TLS) encrypt DNS queries, preventing eavesdropping. Configure your resolvers to support encrypted DNS.') }], conclusion: 'DNS security protects users from spoofing and surveillance. Implement DNSSEC and support encrypted DNS resolvers.' },
  ],
  'Cybersecurity': [
    { title: 'Penetration Testing: Complete Methodology', slug: 'penetration-testing-methodology', intro: 'Penetration testing simulates real-world attacks to identify vulnerabilities. This guide covers the complete methodology from planning to reporting.', sections: [{ heading: 'Pentesting Phases', content: ol(['<strong>Planning:</strong> Define scope and rules of engagement', '<strong>Reconnaissance:</strong> Gather target information using OSINT', '<strong>Scanning:</strong> Identify open ports and vulnerabilities', '<strong>Exploitation:</strong> Attempt to gain access', '<strong>Post-Exploitation:</strong> Determine impact', '<strong>Reporting:</strong> Document findings and remediation']) }, { heading: 'Essential Tools', content: ul(['<strong>Nmap:</strong> Network scanning', '<strong>Burp Suite:</strong> Web application testing', '<strong>Metasploit:</strong> Exploitation framework', '<strong>Wireshark:</strong> Packet analysis', '<strong>sqlmap:</strong> SQL injection testing']) }], conclusion: 'Penetration testing is critical for security programs. Follow a methodology and communicate findings clearly.' },
    { title: 'Vulnerability Scanning Tools and Strategies', slug: 'vulnerability-scanning-tools', intro: 'Vulnerability scanning automates identification of security weaknesses. Regular scanning is essential for maintaining a strong security posture.', sections: [{ heading: 'Types of Scanners', content: p('Network scanners (Nessus, OpenVAS), web application scanners (OWASP ZAP, Burp), and container scanners (Trivy, Snyk) each serve different purposes.') }], conclusion: 'Vulnerability scanning is foundational. Automate scanning, prioritize findings, and track remediation.' },
    { title: 'Zero Trust Architecture: Implementation Guide', slug: 'zero-trust-architecture-guide', intro: 'Zero Trust assumes no implicit trust and requires continuous verification. It is the modern approach to enterprise security.', sections: [{ heading: 'Core Principles', content: p('Verify explicitly, use least privilege access, and assume breach. Implement across identities, devices, applications, data, network, and infrastructure.') }], conclusion: 'Zero Trust is a journey. Start with strong identity verification and expand gradually.' },
    { title: 'SIEM Tools: Security Information and Event Management', slug: 'siem-tools-guide', intro: 'SIEM solutions aggregate and analyze security logs to detect threats, support incident response, and maintain compliance.', sections: [{ heading: 'Top SIEM Solutions', content: ul(['<strong>Splunk:</strong> Industry leader with powerful analytics', '<strong>Elastic SIEM:</strong> Open-source based', '<strong>Microsoft Sentinel:</strong> Cloud-native', '<strong>Wazuh:</strong> Open-source SIEM/XDR']) }], conclusion: 'A SIEM is essential for modern security operations. Choose a solution that fits your size and budget.' },
    { title: 'Incident Response Planning and Execution', slug: 'incident-response-planning', intro: 'An incident response plan defines procedures for detecting, investigating, and remediating security incidents.', sections: [{ heading: 'IR Lifecycle', content: ol(['Preparation', 'Detection and Analysis', 'Containment', 'Eradication and Recovery', 'Post-Incident Activity']) }], conclusion: 'The quality of your IR depends on preparation. Regularly test and update your plan.' },
    { title: 'Ransomware Protection and Recovery', slug: 'ransomware-protection-recovery', intro: 'Ransomware attacks are devastating. Prevention, detection, and recovery strategies are essential for organizational protection.', sections: [{ heading: 'Prevention Strategies', content: p('Implement email filtering, EDR, network segmentation, regular patching, and user awareness training.') }, { heading: 'Backup Strategy', content: p('Follow the 3-2-1 rule: three copies, two different media, one offsite. Test backups regularly and implement immutable backups.') }], conclusion: 'Ransomware protection requires comprehensive strategy spanning prevention, detection, backup, and recovery.' },
    { title: 'Password Managers: Enterprise and Personal Solutions', slug: 'password-managers-guide', intro: 'Password managers maintain strong, unique passwords across all accounts. This guide covers enterprise and personal solutions.', sections: [{ heading: 'Enterprise Solutions', content: ul(['<strong>1Password Business:</strong> Excellent UX with breach monitoring', '<strong>Bitwarden:</strong> Open-source with self-hosting', '<strong>Dashlane Business:</strong> Dark web monitoring included', '<strong>Keeper Enterprise:</strong> Zero-knowledge encryption']) }], conclusion: 'A password manager is non-negotiable for security. Choose one and use it consistently.' },
    { title: 'Two-Factor and Multi-Factor Authentication', slug: '2fa-mfa-authentication-guide', intro: 'MFA adds critical layers of security beyond passwords. This guide covers implementation strategies.', sections: [{ heading: 'MFA Methods by Security', content: ol(['<strong>Hardware keys (FIDO2):</strong> Most secure, phishing-resistant', '<strong>Authenticator apps (TOTP):</strong> Good balance', '<strong>Push notifications:</strong> Convenient but vulnerable to fatigue', '<strong>SMS codes:</strong> Vulnerable to SIM swapping']) }], conclusion: 'MFA is one of the most effective security controls. Implement it broadly and prefer hardware keys.' },
    { title: 'SOC Operations: Security Operations Center', slug: 'soc-operations-guide', intro: 'A SOC is the centralized function for monitoring, detecting, and responding to cybersecurity incidents.', sections: [{ heading: 'SOC Structure', content: p('Tier 1 (triage), Tier 2 (investigation), Tier 3 (threat hunting), SOC manager, and threat intelligence analysts. 24/7 coverage requires shift-based staffing.') }], conclusion: 'A well-functioning SOC requires investment in people, processes, and technology equally.' },
    { title: 'Threat Modeling: Frameworks and Methodologies', slug: 'threat-modeling-frameworks', intro: 'Threat modeling identifies potential threats during design phase, preventing issues before code is written.', sections: [{ heading: 'Methodologies', content: ul(['<strong>STRIDE:</strong> Spoofing, Tampering, Repudiation, Information Disclosure, DoS, Elevation of Privilege', '<strong>PASTA:</strong> Risk-centric, 7-step process', '<strong>Attack Trees:</strong> Graphical attack paths']) }], conclusion: 'Threat modeling shifts security left. Make it a regular part of your development lifecycle.' },
    { title: 'Email Security: SPF, DKIM, and DMARC', slug: 'email-security-spf-dkim-dmarc', intro: 'SPF, DKIM, and DMARC work together to prevent email spoofing and protect domain reputation.', sections: [{ heading: 'Implementation Steps', content: ol(['Create SPF record listing authorized senders', 'Set up DKIM signing for outgoing mail', 'Configure DMARC with p=none initially', 'Analyze reports and move to quarantine/reject']) }], conclusion: 'Proper email authentication protects your domain from spoofing and improves deliverability.' },
    { title: 'Security Auditing and Compliance Frameworks', slug: 'security-auditing-compliance', intro: 'Security audits and compliance frameworks provide structured approaches to assessing and maintaining security.', sections: [{ heading: 'Major Frameworks', content: ul(['SOC 2, ISO 27001, HIPAA, PCI DSS, GDPR, FedRAMP']) }], conclusion: 'Compliance provides structure for security programs. Focus on genuine improvement, not just passing audits.' },
    { title: 'Application Security Testing: SAST, DAST, IAST', slug: 'application-security-testing-guide', intro: 'Application security testing identifies vulnerabilities throughout the development lifecycle.', sections: [{ heading: 'Testing Approaches', content: ul(['<strong>SAST:</strong> Static code analysis (SonarQube, Semgrep)', '<strong>DAST:</strong> Dynamic testing (OWASP ZAP, Burp)', '<strong>IAST:</strong> Interactive analysis (Contrast Security)', '<strong>SCA:</strong> Software composition analysis (Snyk, Dependabot)']) }], conclusion: 'Comprehensive testing uses multiple approaches throughout the SDLC. Automate and integrate into your workflow.' },
    { title: 'Social Engineering: Prevention and Awareness', slug: 'social-engineering-prevention', intro: 'Social engineering exploits human psychology rather than technical vulnerabilities. It remains the most effective attack vector.', sections: [{ heading: 'Attack Types', content: ul(['Phishing, Spear Phishing, Pretexting', 'Baiting, Tailgating, Vishing', 'CEO Fraud, Watering Hole Attacks']) }], conclusion: 'Technology alone cannot prevent social engineering. Invest in comprehensive awareness training.' },
  ],
};

export default TOPICS;

async function seed() {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) { console.error('DATABASE_URL not set'); process.exit(1); }

  const pool = new Pool({ connectionString, ssl: false });
  const db = drizzle(pool, { schema });

  console.log('[Seed Content] Generating 150 content pages...');

  let count = 0;
  for (const [category, topics] of Object.entries(TOPICS)) {
    for (const topic of topics) {
      try {
        await db.insert(schema.contentPages).values(
          buildPage(topic, category)
        ).onConflictDoNothing();
        count++;
      } catch (e) {
        console.error(`Failed: ${topic.slug}`, e);
      }
    }
    console.log(`[Seed Content] ${category}: ${topics.length} pages`);
  }

  // Generate remaining categories programmatically to reach 150
  const remainingCategories: Record<string, string[]> = {
    'Cloud Computing': ['AWS vs Azure vs GCP Comparison', 'Kubernetes Deployment Guide', 'Docker Production Best Practices', 'Serverless Architecture Guide', 'Cloud Cost Optimization', 'Multi-Cloud Strategy', 'Cloud Migration Strategies', 'Infrastructure as Code with Terraform', 'Cloud Security Shared Responsibility', 'Edge Computing Architecture', 'Cloud Networking VPC Design', 'Cloud Storage Types Guide', 'Serverless Databases Guide', 'Cloud Identity and Access Management', 'Cloud Compliance and Governance'],
    'AI & Machine Learning': ['Neural Networks Explained', 'LLM Fine-Tuning Guide', 'Computer Vision Guide', 'NLP Pipelines Guide', 'MLOps Guide', 'AI Ethics Responsible Development', 'TensorFlow vs PyTorch Comparison', 'Generative AI Guide', 'Reinforcement Learning Guide', 'AI in Healthcare Applications', 'Transfer Learning Guide', 'AutoML Guide', 'Feature Engineering for ML', 'Deep Learning Optimization', 'AI Model Deployment Strategies'],
    'Databases': ['PostgreSQL Optimization Guide', 'MongoDB Scaling Strategies', 'Redis Caching Strategies', 'Database Indexing Guide', 'SQL vs NoSQL Database Choice', 'Database Replication Guide', 'Database Backup and Recovery', 'SQL Query Optimization', 'Time-Series Databases Guide', 'Graph Databases Guide', 'Database Connection Pooling', 'Data Modeling Database Schemas'],
    'Linux': ['Linux Command Line Mastery', 'Systemd Services Guide', 'Bash Scripting Guide', 'Linux Security Hardening', 'Package Management Guide', 'Linux Kernel Compilation', 'Linux File Permissions ACLs', 'Cron Jobs Scheduling Guide', 'Linux Log Management', 'Linux Networking Configuration', 'SSH Mastery Configuration', 'Linux Process Management'],
    'Web Development': ['React Best Practices', 'Next.js vs Remix Comparison', 'REST API Design Patterns', 'WebSocket Real-Time Apps', 'Web Performance Optimization', 'Web Accessibility Guide', 'CSS Grid Flexbox Mastery', 'Progressive Web Apps Guide', 'SEO for Developers Guide', 'Web Security OWASP Guide', 'TypeScript Advanced Patterns', 'State Management Solutions'],
    'DevOps': ['CI/CD Pipeline Guide', 'GitOps Workflow Guide', 'Prometheus Grafana Monitoring', 'ELK Stack Log Aggregation', 'Infrastructure as Code Guide', 'Blue-Green Deployments', 'Chaos Engineering Guide', 'SRE Practices Guide', 'Container Orchestration Guide', 'Artifact Management Guide', 'DevOps Culture and Practices', 'GitOps with ArgoCD'],
    'Mobile Development': ['React Native vs Flutter', 'Mobile App Security Guide', 'Push Notifications Implementation', 'App Store Optimization Guide', 'Offline-First Design Patterns', 'Mobile Testing Strategies', 'Cross-Platform Performance'],
    'Health Tech': ['Telemedicine Platforms Guide', 'EHR EMR Systems Guide', 'HIPAA Compliance Guide', 'Wearable Technology Guide', 'AI Diagnostics in Healthcare', 'Medical Imaging Technology', 'Health Data Interoperability HL7 FHIR', 'Remote Patient Monitoring', 'Mental Health Apps Guide', 'Biotech Data Analysis'],
    'Hardware': ['Building a Home Server', 'NAS Setup Guide', 'Raspberry Pi Projects Guide', 'GPU Computing Guide', 'SSD vs HDD Performance'],
    'Data Science': ['Data Pipeline Architecture', 'D3.js Visualization Guide', 'Statistical Analysis Python', 'Big Data Spark Guide', 'Data Governance Framework'],
  };

  for (const [category, titles] of Object.entries(remainingCategories)) {
    for (const title of titles) {
      const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
      const intro = `A comprehensive guide to ${title.toLowerCase()}. This article covers fundamental concepts, practical implementations, best practices, and expert insights to help you master this topic.`;
      const sections = [
        { heading: 'Introduction and Overview', content: p(`Understanding ${title.toLowerCase()} is essential in today's technology landscape. This guide provides a thorough exploration of the topic, covering everything from basic concepts to advanced implementations. Whether you're a beginner looking to learn the fundamentals or an experienced professional seeking to deepen your knowledge, this guide has something for everyone.`) + p('The field continues to evolve rapidly, with new tools, frameworks, and best practices emerging regularly. Staying current with these developments is crucial for maintaining competitive advantage and delivering high-quality results.') },
        { heading: 'Core Concepts', content: p('At the heart of this topic are several key concepts that form the foundation of understanding. These include the fundamental principles, common patterns, and established best practices that practitioners rely on daily.') + ul(['Understanding the fundamental architecture and design patterns', 'Key terminology and concepts every practitioner should know', 'How different components interact and work together', 'Common workflows and operational procedures', 'Performance considerations and optimization strategies', 'Security implications and best practices']) },
        { heading: 'Practical Implementation', content: p('Moving from theory to practice requires understanding the step-by-step implementation process. This section walks through the practical aspects, including setup, configuration, and deployment considerations.') + ol(['Set up your development environment with the necessary tools', 'Configure the core components according to best practices', 'Implement the solution following established patterns', 'Test thoroughly to ensure reliability and correctness', 'Deploy to production with appropriate monitoring', 'Maintain and iterate based on feedback and metrics']) },
        { heading: 'Best Practices and Standards', content: p('Industry best practices have been developed through years of experience and countless real-world implementations. Following these practices helps avoid common pitfalls and ensures your implementation is robust, maintainable, and scalable.') + ul(['Follow established naming conventions and coding standards', 'Implement comprehensive logging and monitoring', 'Use automated testing at all levels (unit, integration, e2e)', 'Document your architecture and decisions thoroughly', 'Plan for scalability from the beginning', 'Implement security measures at every layer']) },
        { heading: 'Advanced Topics', content: p('Once you have mastered the fundamentals, several advanced topics can help you take your skills to the next level. These topics build upon the core concepts and require a solid understanding of the basics.') + p('Advanced practitioners should focus on optimization, scalability patterns, edge case handling, and integration with other systems. Continuous learning and staying updated with the latest developments is essential.') },
        { heading: 'Tools and Resources', content: p('The ecosystem around this topic includes numerous tools, libraries, and resources. Choosing the right tools for your specific use case is important for productivity and success.') + p('Community resources like Stack Overflow, GitHub repositories, and official documentation are invaluable for troubleshooting and learning. Engaging with the community through forums, meetups, and conferences helps you stay connected with the latest developments.') },
      ];

      try {
        await db.insert(schema.contentPages).values(
          buildPage({ title, slug, intro, sections, conclusion: `Mastering ${title.toLowerCase()} requires a combination of theoretical understanding and practical experience. Start with the fundamentals, practice regularly, and gradually tackle more advanced topics. The resources and community around this topic are excellent - take advantage of them to accelerate your learning journey.` }, category)
        ).onConflictDoNothing();
        count++;
      } catch (e) {
        console.error(`Failed: ${slug}`, e);
      }
    }
    console.log(`[Seed Content] ${category}: ${titles.length} pages`);
  }

  console.log(`[Seed Content] Total pages generated: ${count}`);
  await pool.end();
}

seed().catch(console.error);
